{{- if .Values.armAuth -}}
{{- if eq .Values.armAuth.type "aadPodIdentity"}}

# Please see https://github.com/Azure/aad-pod-identity for more inromation
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: ##NAME##
spec: 
  AzureIdentity: ##AZUREIDENTITY##
  Selector: ##SELECTOR##

{{- end}}
{{- end}}