apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phippy-phippy
  labels:
    draft: draft-app
    chart: phippy-phippy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        draft: draft-app
        app: phippy-phippy
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: phippy
        image: ##clustername##.azurecr.io/phippy:##phippyversion##
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3333
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
