apiVersion: v1
kind: Service
metadata:
  name: phippy-phippy
  labels:
    chart: phippy-phippy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3333
    protocol: TCP
    name: phippy-phippy
  selector:
    app: phippy-phippy
