apiVersion: v1
kind: Secret
metadata:
  name: parrot-acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhZG84cmVnLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhZG84cmVnIiwicGFzc3dvcmQiOiJhRUx4U3JzekZKQlFuczRyPWN2d2c1Q1RBaHZjSFc0YyIsImF1dGgiOiJZV1J2T0hKbFp6cGhSVXg0VTNKemVrWktRbEZ1Y3pSeVBXTjJkMmMxUTFSQmFIWmpTRmMwWXc9PSJ9fX0=
  
