apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhZG81cmVnLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhZG81cmVnIiwicGFzc3dvcmQiOiJPNlMzL3MvVVJNWDVhaFc0MHpaTk9ib211dDVuWDlTNCIsImF1dGgiOiJZV1J2TlhKbFp6cFBObE16TDNNdlZWSk5XRFZoYUZjME1IcGFUazlpYjIxMWREVnVXRGxUTkE9PSJ9fX0=
  
  
