apiVersion: v1
kind: Service
metadata:
  name: parrot-parrot
  labels:
    app: parrot-parrot
    chart: parrot-parrot
    release: parrot
    heritage: parrot-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: parrot-parrot
  type: LoadBalancer
