apiVersion: apps/v1
kind: Deployment
metadata:
  name: captainkube-captainkube
  labels:
    app: captainkube-captainkube
    chart: captainkube-captainkube
    release: captainkube
    heritage: captainkube-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captainkube-captainkube
  template:
    metadata:
      labels:
        app: captainkube-captainkube
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: captainkube
        image: ado5reg.azurecr.io/captainkube:##captainkubeversion##
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3


