apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebrady-nodebrady
  labels:
    app: nodebrady-nodebrady
    chart: nodebrady-nodebrady
    release: nodebrady
    heritage: nodebrady-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebrady-nodebrady
  template:
    metadata:
      labels:
        app: nodebrady-nodebrady
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: nodebrady
        image: ##clustername##.azurecr.io/nodebrady:##nodebradyversion##
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
