apiVersion: v1
kind: Service
metadata:
  name: nodebrady-nodebrady
  labels:
    app: nodebrady-nodebrady
    chart: nodebrady-nodebrady
    release: nodebrady
    heritage: nodebrady-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodebrady-nodebrady
  type: ClusterIP